### ISSUE TITLE
Zpocalypse [1.8] | #CUSTOM GAME

### ISSUE THREAD

**Issue by Chalwk77** [Chalwk77/HALO-SCRIPT-PROJECTS#59] opened 2019-10-03 20:23 UTC
# Zpocalypse:
### Game Play Mechanics:
- Blue Team play as the "zombies".
- Red Team play as the "humans".
- Zombies wield a "skull" with which they melee humans.
- When a human is killed by a zombie they become a zombie themselves.
- When all players have become a zombie the game will end.
- Zombies are lighting fast and slightly stronger than humans.
- Zombies have the ability to camouflage themselves when they crouch.
- The last human alive will have special abilities, such as regenerating health, camouflage and super speed among other things.
- Zombie Assistance: If enabled, a zombie that is killed 7 times consecutively will trigger a random human to be selected as a zombie to assist fellow zombies.
- If the only zombie leaves, a random human will be selected to become a zombie.
- If all humans quit the game, a zombie will be selected to become a human.

### [DL Link](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/CUSTOM%20GAMES/Zpocalypse%20(v1.8).lua)

**Comment by Dark3211** [comment] 2019-10-04 19:48
Bug

EventCallback >> OnPlayerDeath >> Lua Error: [string "Zpocalypse"]:556: bad argu
ment #2 to 'rprint' (string expected, got nil)

This happens when you kill any human and if it's the last one, the game doesn't end.



Another mistake, or I don't know if it is, is that when the game starts and there are 3 or more players, there are always 2 zombies instead of 1, as I said I don't know if this is a mistake or not, but I inform you in case of Let it be.

**Comment by Chalwk77** [comment] 2019-10-04 21:11
Fixed (:

**Comment by Dark3211** [comment] 2019-10-05 05:06
The first error was corrected. but... I tried the script again with 10 players and at the start of the game there are 5 zombies and 5 humans I don't know if this is a mistake or so is the script configuration, if it is the script configuration, where i modify it so that there is only 1 zombie when starting the game?

**Comment by Chalwk77** [comment] 2019-10-05 05:19
This was not a mistake and there isn't a configuration option for it.
However, I will make a configuration option for it...

Will update you here.

**Comment by Chalwk77** [comment] 2019-10-12 23:09
Oh wow. I totally forgot about this. Sorry, I've been so busy with other things.
I'll get this done today!

**Comment by Chalwk77** [comment] 2019-10-12 23:56
Zombies has been updated with a new config option on line 49 "balance_teams" - which is OFF by default now.

**Comment by Dark3211** [comment] 2019-10-13 22:22
Bug

The zombie weapon falls

**Comment by Chalwk77** [comment] 2019-10-14 01:17
Fixed.

**Comment by Chalwk77** [comment] 2019-10-14 04:02
Updated again with changes to the message outputs.
There are a couple of new config settings + tidied up some code.

**Comment by Chalwk77** [comment] 2019-10-14 04:46
Updated again with a bug fix.
* When the second-to-last human quits, the remaining human will now become "the last man standing".

**Comment by Dark3211** [comment] 2019-10-14 05:10
Hi! I don't want to bother you ... but it is possible to add:




[+] Human weapons settings. 

Example: 
Human_Weapon [1] = "weapons \pistol\pistol"
Human_Weapon [2] = "weapons\sniper rifle\sniper rifle" Human_Weapon [3] = "weapons\shotgun\shotgun"
Human_Weapon [4] = nil 




[+] Without zombies.

 If the only zombie leaves, a random (human) player is passed to the Zombie team after 5 seconds.

Msg = "The zombie is a coward and left, someone will be changed to take his place in ...% seconds%".





[+] Help the zombie.

If the only zombie is killed 7 or 8 times, a Human (random) is passed after 5 seconds to help him (This does not happen if there is more than 1 zombie).

Msg = "The zombie is very bad, someone will be changed to help you in ...% seconds%".




[+] Score Per Second. (This is not really necessary) 

Human_Score = 2 - (Seconds) Zombie_Score = 1 - (Seconds) 

Thanks!

**Comment by Chalwk77** [comment] 2019-10-14 21:49
[bug fix]

Fixed a bug where humans would be assigned a skull when switching weapon.

**Comment by Chalwk77** [comment] 2019-10-14 23:47
[new feature]

You can now optionally toggle human weapon assignment on or off on a per-map basis.
Humans can spawn with up to 4 weapons. See config section for details.

**Comment by Chalwk77** [comment] 2019-10-15 00:58
Updated with another bug fix and small tweaks.

**Comment by Chalwk77** [comment] 2019-10-15 01:37
[new feature]

Zombie Assistance:
If enabled, zombies who are killed "assistance_threshold" times will trigger a random human to be switch to the zombie team to assist (excludes the last man standing).

**Comment by Dark3211** [comment] 2019-10-15 06:40
Do not add the ~~Score Per Second~~, I do not know what I thought when I made this request, I do not see the logic. :P

**Comment by Chalwk77** [comment] 2019-10-15 11:14
Beta V1.3 has been in development for the last 15 hours. I have rewritten a massive chunk of code and this comes with potentially a few bugs. If you want to test Beta V1.3 the download link is here:
### [beta v1.3](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/INDEV/Zpocalypse%20(beta%20v1.3).lua)
### [Click to View Changes](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/commit/fdeb0de35b7cecfd65df87a2670fe47c93491e39)
Beta V1.3 will be uploaded as a full release when it's bug-free.

**Comment by Dark3211** [comment] 2019-10-15 17:50
Zpocalypse (beta v1.2)

Bugs:

EventCallback >> OnTick >> Lua Error: [string "Zpocalypsev1.2"]:317: bad argument #1 to 'pairs' (table expected, got nil)

EventCallback >> OnGameStart >> Lua Error: [string "Zpocalypsev1.2"]:201: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by Dark3211** [comment] 2019-10-15 19:13
Zpocalypse (beta v1.3)
Bug:

EventCallback >> OnTick >> Lua Error: [string "Zpocalypsev1.3"]:1101: bad argument
#3 to 'gsub' (string/function/table expected)

**Comment by Chalwk77** [comment] 2019-10-15 21:06
1.3 will be released in a couple of hours (bug free).
Many changes to the message outputs.
Performance improvements.
Bug fixes.
Epic.

**Comment by Chalwk77** [comment] 2019-10-15 22:20
Beta v1.3 released.

**Comment by Dark3211** [comment] 2019-10-17 02:05
Bug

The human's weapons are not assigned.

**Comment by Chalwk77** [comment] 2019-10-17 03:09
I can't seem to reproduce that bug. It is working fine for me. Does weapon assignment not work on all maps? Can you upload your version of the script?

**Comment by Dark3211** [comment] 2019-10-17 03:53
I have the current version of the script, maybe I modified something wrong, tomorrow I will download the script and try again

**Comment by Dark3211** [comment] 2019-10-17 18:38
I tried again and it does the same on some maps if I change my weapons, but in most I have reserve weapons (pistol and assault rifle).

Also ... the "cured zombie" function stopped working. 

Sometimes this error is reproduced: 

stack traceback:
    [string "Zpocalypsebetav1.3"]:1436: in function <[string "Zpocalypsebetav1.3"]:1435>
    [C]: in function '__newindex'
    [string "Zpocalypsebetav1.3"]:788: in function 'SwitchTeam'
    [string "Zpocalypsebetav1.3"]:1068: in function 'setTeam'
    [string "Zpocalypsebetv1.3"]:1024: in function 'sortPlayers'
    [string "Zpocalypsebetav1.3"]:431: in function <[string "Zpocalypsebetav1.3"]:316>

**Comment by Chalwk77** [comment] 2019-10-18 00:32
Updated to v1.4.
Fixed zombie cure and a few other things.

I was unable to reproduce the human weapon assignment bug that you mentioned.
Are you running it on stock maps? What specific maps does weapon assignment fail and when does it fail? Does it fail after the pre-game countdown has elapsed and/or when a human spawns?

**Comment by Chalwk77** [comment] 2019-10-18 05:41
Updated again to fix an issue that was causing a server crash.

**Comment by Dark3211** [comment] 2019-10-18 22:44
I tried the download again.
(the last update)

Bugs:

Weapons are already assigned to humans, but after 2 or 3 games (I tested it with 10 players)
The weapons of humans cease to be assigned (they appear with the weapons of the map (pistol and assault rifle) at the beginning of the game, by infecting the last human sometimes the game does not end.

 (This happens on all stock maps and weapons are not assigned after starting the game "Zpocalypse")

**Comment by Dark3211** [comment] 2019-10-18 23:56
It works, sorry the mistake was mine.

**Comment by Dark3211** [comment] 2019-10-19 00:23
The human's weapon assignment works, the mistake was mine.

 But I have this error: 
(Add 2 maps, so the error lines may be affected)

stack traceback:     [string "Zpocalypse1.3"]: 1417: in function <[string "Zpocalypse1.3"]: 1416>     [C]: in function '__newindex'     [string "Zpocalypse1.3"]: 792: in function 'SwitchTeam'     [string "Zpocalypse1.3"]: 1072: in function 'setTeam'     [string "Zpocalypse1.3"]: 1028: in function 'sortPlayers'     [string "Zpocalypse1.3"]: 434: in function <[string "Zpocalypse1.3"]: 319>

(This occurs when a player enters just 1 second before the game starts).

**Comment by Chalwk77** [comment] 2019-10-19 08:23
Updated to Beta V 1.5 to fix the error reported above.

**Comment by Chalwk77** [comment] 2019-10-19 21:32
Updated to Full Release (Version 1.0)

Changes: One bug fix.
As long as there are no more bugs this mod will no longer be developed.

**Comment by Dark3211** [comment] 2019-10-19 22:54
Hi.
Were these errors corrected in the latest updates?

Mistakes: 

Zombie Assistance:
This still runs when there are more than 2 zombies. 

No zombies:
(This happens sometimes
When there are many zombies and one goes out, the sequence of "No Zombies" starts and if the last human is infected, the game does not end.

(This was tested with 13 players)

**Comment by Chalwk77** [comment] 2019-10-20 02:32
Fixed all of the above.

**Comment by Dark3211** [comment] 2019-10-20 22:36
New Errors:

(This occurs when it affects humans and the game does not end)

stack traceback:
    [string "Zpocalypsev1.1"]:1419: in function <[string "Zpocalypsev1.1"]:1418>
    [C]: in function '__le'
    [string "Zpocalypsev1.1"]:686: in function <[string "Zpocalypsev1.1"]:640>

(This happens when sapp surcharge and there are players) 

stack traceback:
    [string "Zpocalypsev1.1"]:1419: in function <[string "Zpocalypsev1.1"]:1418>
    [C]: at 0x10066090
    [C]: in function 'get_var'
    [string "Zpocalypsev1.1"]:296: in function <[string "Zpocalypsev1.1"]:276>

**Comment by Chalwk77** [comment] 2019-10-20 22:55
Whoops. Sorry about that.
Fixed both errors.

**Comment by Dark3211** [comment] 2019-10-21 03:05
Option to disable "Disabling Kill  Messages" or the elimination of this function, since Sapp does not support "unicode" letters and player names look bad.

Some names look like this:
(Example)
"??@#?$? was killed by ??•«???»???"

 Please.

**Comment by Dark3211** [comment] 2019-10-21 04:59
I know it's a lot to ask for this and it can be even annoying, but I liked it when the script was simpler.


Could you eliminate all this ?:

zombie_vs_human_lastman = "%victim% was Zombified by %killer%. %lastman% is the Last Human Alive!"

human_falldamage = "%victim% died and was Zombified!",

human_falldamage_lastman = "%victim% died and was Zombified. %lastman% is the Last Human Alive!"

zombie_falldamage = "%victim% died"

human_distancedamage = "%victim% fell and was Zombified!",

human_distancedamage_lastman = "%victim% fell and was Zombified. %lastman% is the Last Human Alive!",

zombie_distancedamage = "%victim% fell and died"

zombie_suicide = "%victim% committed suicide"

human_vs_zombie = "%victim% was killed by %killer%"

human_suicide = "%victim% committed suicide and was Zombified!"

human_suicide_lastman = "%victim% committed suicide. %lastman% is the Last Human Alive!"


Only the simple ones remain:

on_zombified = "was Zombified"
(This is shown either when the human commits suicide, is infected, falldamage, died, etc ... without replacing the original messages of the game)

last_man = "% lastman% is the Last Human Alive!"

Thanks!

**Comment by Chalwk77** [comment] 2019-10-21 06:03
> Option to disable "Disabling Kill Messages" or the elimination of this function, since Sapp does not support "unicode" letters and player names look bad.
> 
> Some names look like this:
> (Example)
> "??@#?$? was killed by ??•«???»???"
> 
> Please.

Player names will appear normal if you convert in ANSI. 
Open the script in Notepad++ and click the Encoding Tab. Select "Convert to ANSI". Save. Reload script.

**Comment by Chalwk77** [comment] 2019-10-21 20:34
> I know it's a lot to ask for this and it can be even annoying, but I liked it when the script was simpler.
> 
> Could you eliminate all this ?:
> 
> zombie_vs_human_lastman = "%victim% was Zombified by %killer%. %lastman% is the Last Human Alive!"
> 
> human_falldamage = "%victim% died and was Zombified!",
> 
> human_falldamage_lastman = "%victim% died and was Zombified. %lastman% is the Last Human Alive!"
> 
> zombie_falldamage = "%victim% died"
> 
> human_distancedamage = "%victim% fell and was Zombified!",
> 
> human_distancedamage_lastman = "%victim% fell and was Zombified. %lastman% is the Last Human Alive!",
> 
> zombie_distancedamage = "%victim% fell and died"
> 
> zombie_suicide = "%victim% committed suicide"
> 
> human_vs_zombie = "%victim% was killed by %killer%"
> 
> human_suicide = "%victim% committed suicide and was Zombified!"
> 
> human_suicide_lastman = "%victim% committed suicide. %lastman% is the Last Human Alive!"
> 
> Only the simple ones remain:
> 
> on_zombified = "%victim% was Zombified"
> (This is shown either when the human commits suicide, is infected, died, etc ... without replacing the original messages of the game)
> 
> last_man = "%lastman% is the Last Human Alive!"
> 
> Thanks!

Done.
### [DL Link (Extended Message Output)](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/CUSTOM%20GAMES/Zpocalypse%20(v1.3).lua)

### [DL Link (Simple Message Output)](https://github.com/Chalwk77/HALO-SCRIPT-PROJECTS/blob/master/SAPP%20SCRIPTS/CUSTOM%20GAMES/Zpocalypse%20(simplified%20v1.3).lua)

There was 1 bug fix as well (for both)

**Comment by Dark3211** [comment] 2019-10-22 05:03
(Zpocalypse Simple v1.3)
Bugs:

Zombie Cured does not work. 

Last Man speed and damage does not work. 
(This was already happening but I never reported it)

**Comment by Chalwk77** [comment] 2019-10-22 21:12
Fixed.

**Comment by Dark3211** [comment] 2019-10-23 20:50
Zpocalypse (Simple v1.4)

Errors:

Zombies Assistance continues to run even if there are already 2 or more zombies.

Sometimes, when infecting LastMan, the game does not end (rarely occurs). 

LastMan's speed is not assigned (damage already works)

**Comment by Dark3211** [comment] 2019-10-28 02:01
Hello.
Will the errors in the script not be corrected?

I solved 2 errors on my own.

Resolved:

Zombie Assistance was still working even if there were already 2 or more zombies.

Lastman was not assigned speed. 

Without resolving:
(I couldn't, I don't know much about this really)

Sometimes, when infecting lastman, the game did not end.

**Comment by Dark3211** [comment] 2019-11-04 15:44
Well, I realized that the mistake that sometimes the game does not end when it infects the Lastman, occurs when players leave, whether they are human or zombie and the game is in progress.

**Comment by Chalwk77** [comment] 2019-11-14 07:08
My sincerest apologies for the long delay on this update.

#### Bug Fixes in Version 1.5

* No-Zombie timer fails to stop counting down even if someone becomes a zombie or joins the server after the game has already started.

* Removed some useless debug code.

RE: "sometimes, when infecting the last man, the game does not end."
* Could not reproduce this error.

**Comment by Chalwk77** [comment] 2019-11-14 22:36
If you experience any issues with this script please be as descriptive as possible when reporting any bugs. For example, under what circumstance causes the issue? I have not been able to reproduce the problem whereby the game doesn't end after the last man is infected. As far as I can tell this is working correctly. Then again, some errors can only be reproduced in a production server environment as many bugs are only encountered circumstantially. I looked very hard at the functions responsible for setting the last man and ending the game and I cannot see how such a circumstance could exist.

**Comment by Chalwk77** [comment] 2019-11-14 22:52
Updated to fix the error mentioned above.
Please let me know if this resolves the issue.

**Comment by Dark3211** [comment] 2019-11-14 23:30
Hi... Well I don't know exactly why this error occurs, but I solved it with an event, I don't have problems anymore.

**Comment by Chalwk77** [comment] 2019-11-14 23:35
Can you explain what you did to solve it? That would be very helpful.

**Comment by Chalwk77** [comment] 2019-11-15 08:10
Just FYI. The latest update should have fixed the issue. I came to the realization shortly I posted third-to-last post.

**Comment by Dark3211** [comment] 2019-11-15 13:34
As I said, I no longer have problems with this.
I solved it with the following event: 

event_die $pn>2 $reds=0 'sv_map_next;say * "The zombies won!"

**Comment by Chalwk77** [comment] 2019-11-17 21:42
## Updated to fix the intermittent issue where the game wouldn't end when the last man is infected.
### Download link in the ticket descriptor.

**Comment by Chalwk77** [comment] 2019-11-18 00:59
Turns out the last update didn't fix the issue but in fact made it worse. However, I finally figured out what the problem was. This has been resolved. Please download Version 1.8.

**Closed** 2019-11-19 02:19 UTC
